In [8]:
import numpy as np
import time

Упражнение 1
На одном графике изобразите время затраченное на вычисление с использованием массивов numpy и стандартных списков в питоне.
Для более точных результатов замеряйте время выполнения функции несколько раз и усредняйте.

Используйте функцию z = 2*x**2 + 4*y

In [29]:
def func1(n):
    x = range(n)
    y = range(n)
    z = [2*x[i]**2 + 4*y[i] for i in range(len(x))]
    return(z)

def func2(n):
    x = np.arange(n)
    y = np.arange(n)
    z = 2*x**2 + 4*y
    return(z)

In [35]:
tasks = [func1, func2]
for func in tasks:
    t = time.time()
    func(1000000)
    print(f"{func.__name__}: {time.time()-t}")

func1: 0.8589675426483154
func2: 0.0034525394439697266


Упражнение 2
Создайте массив чисел от 2 до 75. Выведите только нечётные.
Присвойте нечётным числам этого массива значение -1.

In [30]:
a = np.arange(2,75)
a[a%2==1]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73])

In [31]:
a[a%2==1] = -1
a

array([ 2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1, 18,
       -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1,
       36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1, 50, -1, 52,
       -1, 54, -1, 56, -1, 58, -1, 60, -1, 62, -1, 64, -1, 66, -1, 68, -1,
       70, -1, 72, -1, 74])

Упражнение 3
Найдите в документации функцию, которая удаляет из одного массива элементы, которые есть в другом.
Приведите примеры использования.

In [232]:
a = np.array([2, 7, 8, 10, 13])
b = np.array([7, 13])

In [233]:
a[b[np.searchsorted(b,a)] !=  a]

array([ 2,  8, 10])

Упражнение 4
Создайте случайную квадратную матрицу случайного размера от 10 до 100.
Найдите максимум и сумму элементов.
Поделите каждый элемент матрицы на максимум.
Отнимите от каждой строки матрицы среднее по строке.
Замените максимальное значение на -1.

In [97]:
size = np.random.randint(10, 100)
a = np.eye(size)+np.random.rand(size)
a

array([[1.69533194, 0.05593564, 0.92686416, ..., 0.79218111, 0.7878138 ,
        0.74954423],
       [0.69533194, 1.05593564, 0.92686416, ..., 0.79218111, 0.7878138 ,
        0.74954423],
       [0.69533194, 0.05593564, 1.92686416, ..., 0.79218111, 0.7878138 ,
        0.74954423],
       ...,
       [0.69533194, 0.05593564, 0.92686416, ..., 1.79218111, 0.7878138 ,
        0.74954423],
       [0.69533194, 0.05593564, 0.92686416, ..., 0.79218111, 1.7878138 ,
        0.74954423],
       [0.69533194, 0.05593564, 0.92686416, ..., 0.79218111, 0.7878138 ,
        1.74954423]])

In [98]:
a.max(), a.sum()

(1.9806290137151532, 1409.797143155338)

In [101]:
a/a.max()

array([[0.85595633, 0.02824135, 0.46796455, ..., 0.39996441, 0.39775939,
        0.37843747],
       [0.35106622, 0.53313146, 0.46796455, ..., 0.39996441, 0.39775939,
        0.37843747],
       [0.35106622, 0.02824135, 0.97285466, ..., 0.39996441, 0.39775939,
        0.37843747],
       ...,
       [0.35106622, 0.02824135, 0.46796455, ..., 0.90485452, 0.39775939,
        0.37843747],
       [0.35106622, 0.02824135, 0.46796455, ..., 0.39996441, 0.9026495 ,
        0.37843747],
       [0.35106622, 0.02824135, 0.46796455, ..., 0.39996441, 0.39775939,
        0.88332758]])

In [102]:
a-a.mean(axis = 1)

array([[ 1.13141308, -0.50798322,  0.3629453 , ...,  0.22826225,
         0.22389494,  0.18562537],
       [ 0.13141308,  0.49201678,  0.3629453 , ...,  0.22826225,
         0.22389494,  0.18562537],
       [ 0.13141308, -0.50798322,  1.3629453 , ...,  0.22826225,
         0.22389494,  0.18562537],
       ...,
       [ 0.13141308, -0.50798322,  0.3629453 , ...,  1.22826225,
         0.22389494,  0.18562537],
       [ 0.13141308, -0.50798322,  0.3629453 , ...,  0.22826225,
         1.22389494,  0.18562537],
       [ 0.13141308, -0.50798322,  0.3629453 , ...,  0.22826225,
         0.22389494,  1.18562537]])

In [104]:
a[a == a.max()] = -1
a

array([[1.69533194, 0.05593564, 0.92686416, ..., 0.79218111, 0.7878138 ,
        0.74954423],
       [0.69533194, 1.05593564, 0.92686416, ..., 0.79218111, 0.7878138 ,
        0.74954423],
       [0.69533194, 0.05593564, 1.92686416, ..., 0.79218111, 0.7878138 ,
        0.74954423],
       ...,
       [0.69533194, 0.05593564, 0.92686416, ..., 1.79218111, 0.7878138 ,
        0.74954423],
       [0.69533194, 0.05593564, 0.92686416, ..., 0.79218111, 1.7878138 ,
        0.74954423],
       [0.69533194, 0.05593564, 0.92686416, ..., 0.79218111, 0.7878138 ,
        1.74954423]])

Упражнение 5
Напишите функцию, которая берет многомерный вещественный массив с пропущенными значениями (np.nan) и возвращает его копию с заполненными пропусками (заменять средним значением всех элементов массива). Если в массиве одни пропущенные значения, заполните их нулями.

In [7]:
a = np.full((2,2,3,4), np.nan, dtype='float')
a[np.isnan(a) == 1] = 0
a

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

Упражнение 6
Напишите функцию которая нормализирует заданный numpy-массив, так чтобы его значения лежали в интервале $[0, 1]$.

In [116]:
def normalization(x):
    x = (x-x.min())/(x.max()-x.min())
    print(x)

In [117]:
a = np.arange(0,100,2)
normalization(a)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


Упражнение 7
Запишите numpy-array в файл.
Считайте numpy-array из файла.

In [120]:
a = np.array([1,2,3,4])
np.save('Ex_7', a)

In [121]:
a = np.load('Ex_7.npy')
a

array([1, 2, 3, 4])

Упражнение 8
Создайте случайный массив
Найдите в массиве элемент ближайший к данному

In [135]:
def find_nearest(a, x):
    a = np.array(a)
    i = (np.abs(a - x)).argmin()
    print(a[i])

In [139]:
find_nearest(np.arange(0,100,0.4), 27)

26.8


Упражнение 9
Напишите функцию, которая возвращает n x m целочисленную матрицу с заданным значением на границах матрицы и с заданным значением внутри

In [211]:
def user_matrix (m,n,i,j):
    a = np.ones((m,n))
    a[:] = i
    a[1:-1,1:-1] = j
    return(a)

In [213]:
user_matrix (4,7,10,100)

array([[ 10.,  10.,  10.,  10.,  10.,  10.,  10.],
       [ 10., 100., 100., 100., 100., 100.,  10.],
       [ 10., 100., 100., 100., 100., 100.,  10.],
       [ 10.,  10.,  10.,  10.,  10.,  10.,  10.]])

Упражнение 10
Напишите функцию, которая сортирует строки данной матрицы по значениям заданного столбца в порядке убывания.

In [224]:
a = np.array([[1, 7, 2], [3, 4, 5]])
a

array([[1, 7, 2],
       [3, 4, 5]])

In [225]:
a[a[:,2][::-1].argsort()]

array([[3, 4, 5],
       [1, 7, 2]])